services:
  mockServer:
    image: mockserver/mockserver:mockserver-5.15.0
    container_name: mock-server
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/data.json
    volumes:
      - ./mockserver/data.json:/config/data.json
  postgres:
    image: 'postgres:16'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=insurancequote'
      - 'POSTGRES_USER=db_user'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'